name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libhdf5-dev \
          libgmp-dev \
          libmpfr-dev \
          libmpc-dev \
          libeigen3-dev;

    - name: Download CADET-semi-analytic dependencies
      run: |
        # Download and build the required libraries if needed
        # Note: Add commands here if any libraries need to be downloaded and built

    - name: Create build directory
      run: mkdir build && cd build

    - name: Run CMake
      working-directory: build
      run: |
        # Set environment variables for CMake to locate libraries
        export GMP_ROOT=/usr/include
        export MPFR_ROOT=/usr/include
        export MPC_ROOT=/usr/include
        export HDF5_ROOT=/usr/include
        cmake -DCMAKE_INSTALL_PREFIX=install/ \
              -DCMAKE_CXX_COMPILER=g++ \
              -DCMAKE_C_COMPILER=gcc \
              -DUSE_FADBAD=ON \
              -DENABLE_TESTS=OFF \
              ..

    - name: Build
      working-directory: build
      run: make -j$(nproc)

    - name: Install
      working-directory: build
      run: make install

    - name: Verify installation
      run: |
        ./build/install/bin/casema-cli --version
