name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit hash, branch name, or tag to run the CI pipeline for'
        required: false
        default: 'HEAD'
        type: string

jobs:
  Windows-latest:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: pwsh # Use PowerShell as the shell
    env:
      SRC_DIR: ${{ github.workspace }}\src
      BUILD_DIR: ${{ github.workspace }}\build
      INSTALL_PREFIX: ${{ github.workspace }}\install
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          path: src
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          cd ..

      - name: Install Dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg install hdf5 gmp mpfr mpc eigen3
          .\vcpkg\vcpkg integrate install # Integrate with CMake

      - name: Create Build and Install Directories
        run: |
          cmake -E make_directory "${env:BUILD_DIR}"
          cmake -E make_directory "${env:INSTALL_PREFIX}"

      - name: Configure CMake
        run: |
          cd "${env:BUILD_DIR}"
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\vcpkg.cmake -DCMAKE_INSTALL_PREFIX="${env:INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE="${env:BUILD_TYPE}" "${env:SRC_DIR}"

      - name: Build and Install
        run: |
          cd "${env:BUILD_DIR}"
          cmake --build . --target install --config ${env:BUILD_TYPE} -- -j %NUMBER_OF_PROCESSORS%

      - name: Check if it runs
        run: |
          $env:LD_LIBRARY_PATH="${env:INSTALL_PREFIX}\lib;$env:LD_LIBRARY_PATH"
          & "${env:INSTALL_PREFIX}\bin\chromatography.exe" --version

      # - name: Run tests
      #   run: |
      #     & "${env:BUILD_DIR}\test\testRunner.exe"
